# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: DeployToVM
  jobs:
  - deployment: InstallApacheAndConfigure
    displayName: "Instalar Apache y Configurar Página"
    
    environment:
      name: "MiEnvironment" # Nombre de tu entorno
      resourceType: VirtualMachine # Tipo de recurso, en este caso una máquina virtual

    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Iniciando instalación de Apache..."
              sudo apt-get update
              sudo apt-get install -y apache2
              echo "Hemos finalizado la prueba" | sudo tee /var/www/html/index.html
              sudo systemctl restart apache2
              echo "Instalación y configuración completadas."
            displayName: "Instalar Apache y Configurar Mensaje"

